---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.5

Layout/LineLength:
  Exclude:
    - test/**/*.rb

Naming/AccessorMethodName:
  Exclude:
    - lib/aitch/request.rb

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
