---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/LineLength:
  Exclude:
    - test/**/*.rb

Naming/AccessorMethodName:
  Exclude:
    - lib/aitch/request.rb

Style/DocumentDynamicEvalDefinition:
  Enabled: false
