---
language: ruby
script: bundle exec rake
before_install: gem install bundler
cache: bundler
sudo: false
rvm:
  - '2.7'
gemfile:
  - Gemfile
notifications:
  email: false
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
env:
  global:
    secure: kYLDjKzCAz7/IGcDTSiMcRxfDPbz2hWsSa5AlriOAbm51RYZpeB/h2HY5BqfuewgRIOxjDnxFnOiv148vsspl5ew6VB8CZjn2zTOthpJ0SC6+GWMbjbcjWyKuwIbpQiwhQxCz8l0SGZWWt53vm1ifgPoYaBvr26xcGWFFGfy890=
